### Openstack Sandbox Details
os_project_id: 0bd7126c14b1416c9070a615782f66a9
os_region_name: RegionOne
os_user_domain_name: Default
os_project_name: pcf
os_identity_api_version: 3
os_password: crowbar
os_auth_url: http://10.182.101.6:5000/v3/
os_username: crowbar
os_interface: public
infra_dns: 10.181.227.181
phani_subnet_cidr: 192.168.143.0/24
dynamic_services_dns: 10.181.227.181


### S3 Object Storage Details (Aka. Minio)
minio_access_key_id: 8607cf0268e8afd102789e54950d840d
minio_secret_access_key: 662845fed038cdd81e3cf6c44c647b01
minio_bucket: pcf-openstack-artifact-cache-latest
minio_endpoint: http://s3.sandbox.pc.innogy.com
minio_output_bucket: pcf-sandbox-terraform

