---
resources:
- name: phani-pipelines 
  type: git
  source:
    uri: https://github.com/cosmo83/phani-pipelines.git
    branch: master

- name: terraform-state
  type: s3
  source:
    access_key_id: {{minio_access_key_id}}
    secret_access_key: {{minio_secret_access_key}}
    endpoint: {{minio_endpoint}}
    bucket: {{minio_output_bucket}}
    regexp: terraform-(.*).tfstate


jobs:
- name: create-phani-infra
  public: true
  ensure:
    put: terraform-state
    params:
      file: create-infrastructure-output/terraform-0.1.1.tfstate
  plan:
  - get: terraform-state
  - get: phani-pipelines
  - task: create-infra
    file: phani-pipelines/tasks/create-infra.yml
    params:
      OS_PROJECT_NAME: {{os_project_name}}
      OS_USERNAME: {{os_username}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      INFRA_DNS: {{infra_dns}}
      PHANI_SUBNET_CIDR: {{phani_subnet_cidr}}
