---
resources:
- name: phani-pipelines 
  type: git
  source:
    uri: https://github.com/cosmo83/phani-pipelines.git
    branch: master

jobs:
- name: create-phani-infra
  public: true
  plan:
  - get: phani-pipelines
  - task: create-infra
    file: phani-pipelines/tasks/create-infra.yml
