---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: phani-pipelines

outputs:
- name: create-infrastructure-output

params:
  OS_PROJECT_NAME:
  OS_USERNAME:
  OS_PASSWORD:
  OS_AUTH_URL:
  OS_REGION_NAME:
  OS_USER_DOMAIN_NAME:
  INFRA_DNS:
  PHANI_SUBNET_CIDR:
  DYNAMIC_SERVICES_DNS:

run:
  path: phani-pipelines/tasks/create-infra.sh 
